### PR TITLE
Feat: Add new language: Brazilian Portuguese

### PR DESCRIPTION
**Pull request by emanuelfranklyn**
Add a new native language to the bot

### CODE REVIEW

**Comment by markokajzer** [comment]
Thank you so much man, this is so awsome!!

Just a quick question. Is there a difference between "brazilian portugese" and "portugese portuguese"?

**Comment by markokajzer** [comment]
Also, feel free to add yourself to the Readme! At the bottom there is a section with acknowledgements :)

**Comment by emanuelfranklyn** [comment]
yes, there is a small difference between European Portuguese and Brazilian Portuguese, but even with this difference both are able to understand what is written since all the words used are the same in both languages

**Comment by emanuelfranklyn** [comment]
and sorry for taking so long to answer

**Comment by markokajzer** [comment]
Thanks again so much and sorry for the long wait. I was feeling a bit burned out over the holidays.

Happy New Year!

**Pull request merged**
