### PR TITLE
Add shuffle command

### PR DESCRIPTION
**Pull request by solar05**

### CODE REVIEW

**Comment by solar05** [comment]
This new command shuffles random <count> sounds in queue, <tag> are optional

**Comment by markokajzer** [comment]
Hey, thank you so much for the contribution!!!

The code is actually looking pretty good, so I'd be fine merging it in. However not sure that a command that just shuffles random stuff into the queue is something anybody would use 😸  I am not using `!random` myself and I never though that I want to shuffle in multiple random sounds.

Is that something that makes sense for you?

Maybe if a few people from our Discord server upvote this PR, I'd be more confident that the bot needs this functionality.

**Comment by solar05** [comment]
Hello!
I have a lot of different entries of friends' phrases, but using `!combo` is inconvenient for me because I need to remember the name of each phrase, and `!random` command selects only one phrase, so I had an idea to add `!shuffle`! After shuffling, you sometimes get very funny sentences :)

**Comment by prenetic** [comment]
This is awesome, I know my friends are going to get a lot of use out of it. Would it make more sense to add this to the existing !random command instead of creating a new command to remember? Just a thought, expanding on what you've already set up with <count> and <tag>.

```
!random
!random 9
!random 4 loudnoises
```

**Pull request closed without merging**
