### PR TITLE
Added link command

### PR DESCRIPTION
**Pull request by mahmedov**

### CODE REVIEW

**Comment by markokajzer** [comment]
Hey man! Really glad about your contribution. What would be the use case of adding the bot to two different servers?

**Comment by mahmedov** [comment]
Most people I talk with like the discord soundbot so when I run the bot, they usually want to add it to other servers of their choice so I figured that they could get the link when I am not online.

**Comment by markokajzer** [comment]
I see! While it would be possible for the bot to join multiple servers at once, there are two drawbacks because of which I ultimately decided not to implement the bot in such a way.

First, currently the bot saves all sounds that are added in one folder. So let's say I had the bot running on server A with my friends and we created 20 sounds. Now, somebody adds the bot to server B and adds new sounds themselves. Since when accessing sounds, e.g. !<sound>, the bot simply checks what sounds are in the folder, server A would now have access to server Bs sounds. Not only could they play them, but also rename, delete. Also ignoring users works in a similar. We could simply exclude users on server B from playing sound, even though we are only on server A.

The second reason is that allowing multiple servers to access the bot would potentially increase the delay between entering a sound and hearing the sound. Since the bot can only join one voice channel, playing sounds is queued. Let's suppose 10 sounds have been queued on server B. At the same time somebody on server A wants to play a sound. They'd have to wait until the whole queue is finished before it would come to A even though this might be 10s of seconds or even multiple minutes.

Hope you understand what I mean, it gets confusing with all the As and Bs. For these reasons however, users will have to create their own bot as described in the Installation part of the Readme unfortunately.

**Comment by mahmedov** [comment]
I totally do, thank you for a nice explanation. I am sorry that I didn't read the readme briefly. I will keep using this feature between my friends.

**Pull request closed without merging**
